# add at top-level to speed local runs
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        args: [--warnings]
        pass_filenames: false
        always_run: true

      - id: quick-test
        name: quick-test
        entry: pytest
        language: system
        types: [python]
        args: [-q, -k, 'not slow']
        pass_filenames: false
        always_run: true

      - id: docs-health
        name: docs-health
        entry: make
        language: system
        args: [health]
        pass_filenames: false
        always_run: true
