site_name: SecFlow Docs

plugins:
  - search
  # mkdocstrings configuration (enabled in M6)
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         paths: [.]
  #         options:
  #           docstring_style: google
  #           show_source: true
  #           show_root_heading: true
  #           show_root_toc_entry: true
  #           show_signature_annotations: true
  #           show_signature_return_annotations: true
  #           separate_signature: true
  #           heading_level: 2
  #           filters: ["!^_"]
  #           members_order: source
  #           merge_init_into_class: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tasklist
  - tables
  - toc:
      permalink: true

extra_javascript:
  - js/mermaid.min.js
  - js/mermaid-init.js

nav:
  - Developer Start Here: developer-start-here.md
  - Governance:
      - Engineering Standards: governance/engineering-standards.md
      - Development Conventions: governance/development-conventions.md
  - API Documentation:
      - Overview: api/README.md
  - Security: security.md
  - Overview:
      - Home: architecture/00-index.md
      - Executive Summary: architecture/01-title-and-executive-summary.md
  - Architecture:
      - Philosophy: architecture/02-architecture-philosophy.md
      - Repository Layout: architecture/03-repository-layout.md
      - Core Packages: architecture/04-core-packages-and-responsibilities.md
      - Orchestration Engine: architecture/05-orchestration-and-workflow-engine.md
      - Plugin System: architecture/06-plugin-system.md
      - Tools Integration: architecture/07-tools-integration-model.md
      - Tool Manager & UX: architecture/08-tool-manager-and-ux-design.md
      - Resource Registry: architecture/09-resource-registry.md
      - Wordlists & Sharing: architecture/10-wordlist-and-output-sharing.md
      - Project Isolation & Sharing: architecture/11-project-isolation-and-data-sharing.md
      - Findings Schema: architecture/12-findings-model-and-schema.md
      - Enrichment Layer: architecture/13-cve-cwe-poc-enrichment-layer.md
      - PoC Sources & Legal: architecture/14-poc-sources-and-legal-guidelines.md
      - Garbage Collection: architecture/15-garbage-collection-and-retention.md
      - Security Model: architecture/16-security-model.md
      - Observability: architecture/17-observability-logging-and-metrics.md
      - Error Handling: architecture/18-error-handling-and-recovery.md
      - Risk Assessment: architecture/19-risk-assessment-framework.md
      - Migration Plan: architecture/20-migration-and-implementation-phases.md
      - CI/CD & Testing: architecture/21-ci-cd-and-testing-strategy.md
      - Dev Experience & Docs: architecture/22-developer-experience-and-docs.md
      - Future Roadmap: architecture/23-future-roadmap.md
      - Final Consensus: architecture/24-final-consensus-summary.md
  - Review & Validation:
      - Guidelines: review/REVIEW_GUIDELINES.md
      - Workflow: review/review_workflow.md
      - Assignments: review/review_assignments.md
      - Checklist: review/validation_checklist.md
      - Status: review/REVIEW_STATUS.md
      - Report: review/validation_report.md
      - AI Summary: review/VALIDATION_SUMMARY.md
      - Mermaid Smoketest: review/mermaid-smoketest.md
