name: ci
on:
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "Makefile"
      - "docs/**"
      - ".github/workflows/**"
jobs:
  # ensure this is the test job used by PRs
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pytest pytest-cov ruff pyright import-linter
          # project extras if present
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install . || true; fi

      - name: Lint
        run: ruff check --output-format=github .

      - name: Type
        run: pyright --warnings

      - name: Import architecture
        run: make imports

      - name: Unit + Coverage
        env:
          MILESTONE: "M0"
        run: |
          pytest -q --maxfail=1 --cov=. --cov-report=term --cov-report=xml
          # extract TOTAL% and enforce dynamic ratchet
          TOTAL=$(coverage report | awk '/TOTAL/ {gsub("%","",$4); print $4}')
          echo "Coverage TOTAL=${TOTAL}%"
          export COVERAGE_PERCENT=$TOTAL
          python scripts/coverage_ratchet.py

      - name: Docs health (conditional)
        run: |
          # If docs changed in this diff, run the health gate
          if git diff --name-only HEAD~1 | grep -E '^docs/|^mkdocs.yml' >/dev/null 2>&1; then
            make health
          else
            echo "Docs unchanged; skipping health gate."
          fi
