name: ci
on:
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "Makefile"
      - "docs/**"
      - ".github/workflows/**"
jobs:
  # Fast-fail order: ruff → pyright → import-linter → unit+coverage → contracts → docs-health → e2e
  ruff:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install ruff
        run: pip install ruff
      - name: Lint (advisory for M0)
        run: ruff --version && ruff check --exit-zero .
  pyright:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: {node-version: '20'}
      - name: Type check (advisory for M0)
        run: npx pyright --version && npx pyright --warnings
  import-linter:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install import-linter
        run: pip install import-linter
      - name: Architecture check (advisory for M0)
        run: import-linter --version && import-linter
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install deps
        run: pip install poetry && poetry install --no-root
      - name: Unit tests
        run: poetry run make unit
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install deps
        run: pip install poetry && poetry install --no-root
      - name: Coverage report
        run: poetry run make coverage
  contract-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install deps
        run: pip install poetry && poetry install --no-root
      - name: Contract tests
        run: poetry run pytest tests/contracts/ -q || echo "Contract tests not implemented yet"
  docs-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install deps
        run: pip install poetry && poetry install --no-root
      - name: Docs health check
        run: poetry run make health
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install deps
        run: pip install poetry && poetry install --no-root
      - name: E2E tests (informational)
        run: poetry run pytest tests/e2e/ -q || echo "E2E tests not implemented yet"
