name: ci
on:
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - "Makefile"
      - "docs/**"
      - ".github/workflows/**"
jobs:
  # ensure this is the test job used by PRs
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install pytest pytest-cov ruff pyright import-linter flask
          # project extras if present
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install . || true; fi

      - name: Lint
        run: ruff check --output-format=github .

      - name: Type
        run: pyright --warnings

      - name: Import architecture
        run: |
          if command -v lint-imports >/dev/null 2>&1; then
            lint-imports
          else
            echo "lint-imports not available; skipping (advisory in M0)"
          fi

      - name: Unit + Coverage
        env:
          MIN_COV: "18"  # M0 baseline; ratchet at M1
        run: |
          pytest -q --maxfail=1 --cov=. --cov-report=term
          # extract TOTAL% and enforce ratchet
          TOTAL=$(coverage report | awk '/TOTAL/ {gsub("%","",$4); print $4}')
          echo "Coverage TOTAL=${TOTAL}% (min ${MIN_COV}%)"
          awk -v t="$TOTAL" -v m="$MIN_COV" 'BEGIN{exit (t+0<m+0)}'

      - name: Docs health (conditional)
        run: |
          # If docs changed in this diff, run the health gate
          if git diff --name-only HEAD~1 | grep -E '^docs/|^mkdocs.yml' >/dev/null 2>&1; then
            make health
          else
            echo "Docs unchanged; skipping health gate."
          fi
