name: coverage
on: [pull_request, push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with: { python-version: '3.11.9' }
      
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      
      - name: Run coverage analysis
        run: |
          pytest --cov=. --cov-report=xml --cov-report=term-missing -q
          COVERAGE_PERCENT=$(coverage report -m | tail -1 | awk '{print $NF}' | tr -d '%')
          echo "COVERAGE_PERCENT=$COVERAGE_PERCENT" >> $GITHUB_ENV
      
      - name: Generate coverage dashboard
        run: python scripts/coverage_dashboard.py
      
      - name: Enforce coverage ratchet
        run: python scripts/coverage_ratchet.py
        env:
          MILESTONE: M1
          COVERAGE_PERCENT: ${{ env.COVERAGE_PERCENT }}
      
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/
            reports/coverage/
