name: coverage
on: { pull_request: {}, push: { branches: [ main ] } }
permissions: { contents: read }
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11.9' }
      - run: python -m pip install --upgrade pip
      - run: pip install -e .
      - run: pip install pytest pytest-cov coverage[toml]
      - run: coverage run -m pytest -q
      - run: coverage report -m
      - run: python scripts/coverage_ratchet.py
        env:
          MILESTONE: M0
          # coverage.py prints "TOTAL ... XX%" — the ratchet reads COVERAGE_PERCENT
          COVERAGE_PERCENT: ${{ steps.coverage_out.outputs.percent }}
