name: coverage
on: [pull_request, push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11.9' }
      - run: python -m pip install --upgrade pip
      - run: pip install -e .
      - run: pip install pytest pytest-cov coverage[toml] requests flask pyyaml
      - run: |
          coverage run -m pytest -q
          COVERAGE_PERCENT=$(coverage report -m | tail -1 | awk '{print $$4}' | tr -d '%')
          echo "COVERAGE_PERCENT=$COVERAGE_PERCENT" >> $GITHUB_ENV
      - run: python scripts/coverage_ratchet.py
        env:
          MILESTONE: M0
          COVERAGE_PERCENT: ${{ env.COVERAGE_PERCENT }}
