name: Enforce GitHub Actions Versions

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  enforce-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enforce GitHub Actions versions
        run: |
          echo "Checking for deprecated GitHub Actions versions..."
          
          # Check for deprecated upload-artifact versions
          if rg -n "actions/upload-artifact@v(2|3)" .github/workflows; then
            echo "❌ Found deprecated actions/upload-artifact version"
            echo "Please update to actions/upload-artifact@v4"
            exit 1
          fi
          
          # Check for other deprecated actions (add as needed)
          if rg -n "actions/checkout@v(1|2)" .github/workflows; then
            echo "❌ Found deprecated actions/checkout version"
            echo "Please update to actions/checkout@v4"
            exit 1
          fi
          
          echo "✅ All GitHub Actions versions are up to date"
