name: Journal Metrics
on:
  push:
    paths:
      - "control/journal/**/*.ndjson"
      - "tools/journal_metrics.py"
  schedule:
    # Run daily at 00:00 UTC to ensure metrics are updated
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Minimal permissions for metrics generation
      contents: write
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # No additional dependencies needed for basic JSON processing
      
      - name: Generate journal metrics
        run: |
          python tools/journal_metrics.py
      
      - name: Commit metrics
        run: |
          git config user.name "secflow-bot"
          git config user.email "secflow-bot@example.com"
          git add reports/daily/**/metrics.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(reports): update journal metrics [skip ci]"
            git push
          fi
      
      - name: Report metrics status
        run: |
          echo "Journal metrics generation completed"
          echo "Check reports/daily/ for updated metrics files"
