name: Project Sync
on:
  issues:
    types: [opened, edited, labeled]
  pull_request:
    types: [opened, edited, labeled, ready_for_review]
jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECTS_TOKEN }}
          script: |
            const contentId = context.payload.pull_request?.node_id || context.payload.issue?.node_id;
            if (!contentId) return;
            await github.graphql(`
              mutation($project:ID!, $content:ID!){
                addProjectV2ItemById(input:{projectId:$project, contentId:$content}){item{id}}
              }`,
              { project: process.env.PROJECTS_V2_ID, content: contentId }
            );
        env:
          PROJECTS_V2_ID: ${{ secrets.PROJECTS_V2_ID }}
  label_by_path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
